version: '1.0'
detection_time: '2025-09-11 19:07:50'
hardware:
  gpu:
  - brand: Intel
    type: integrated
    detected: true
  cpu:
    brand: Intel
    name: Intel64 Family 6 Model 197 Stepping 2, GenuineIntel
    cores: '14'
    arch: AMD64
  os: Windows 11
  detection_stage: initial
